config/routes.rb
Rails.application.routes.draw do

  # Root page
  root 'home#index'

  # Foros y comentarios
  # resources :sections do
  #   resources :forums do
  #     resources :coments
  #   end
  # end

  # Foros 
  resources :forums do
    resources :comments
  end

  # Ads (anuncios)
  resources :ads

  # Archivos y calificaciones
  resources :archives

  resources :alumnos
  resources :personals
   
  get '/return_tought' => 'home#return_tought', :as => :return_tought

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions:      'users/sessions'
  }

  devise_scope :user do
    get 'access',        to: 'users/registrations#access'
    put 'access_update', to: 'users/registrations#access_update'
  end

  namespace :admin do
    resources :news, only:[:index, :new, :create, :edit, :update, :destroy]
    resources :subjects
    resources :users, only:[:index, :new, :create, :edit, :update, :destroy]
    resources :sections
    resources :thoughts, only:[:index, :new, :create, :edit, :update, :destroy]
    resources :emails, only:[:index, :destroy]
    get "students_users_with_not_section" => "sections#students_users_with_not_section", :as => :students_users_with_not_section
    get "professors_with_subjects" => "sections#professors_with_subjects", :as => :professors_with_subjects
    get "section_professor_consult/:id" => "sections#section_professor_consult", :as => :section_professor_consult
    patch  "reset_password/:id" => "users#reset_password", :as => :reset_password
    get "send_email_representing" => "users#send_email_representing", :as => :send_email_representing
    get "send_mm_email" => "users#send_mm_email", :as => :send_mm_email
    get "send_ms_email" => "users#send_ms_email", :as => :send_ms_email
    get "check_mode" => "admin#check_mode", :as => :check_mode
    get "update_mode" => "admin#update_mode", :as => :update_mode
  end

  
  # devise_for :users
  # get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  match '*path' => 'application#error_redirect', via: :all
end

app/models/subject.rb
class Subject < ApplicationRecord

	has_many :profesor_subject, dependent: :destroy
  	has_many :users, through: :profesor_subject

	def self.is_numeric(number)
  	return true if number =~ /^\d+$/
  	true if Float(number) rescue false
	end

	validates :name, presence: {message: "can't be blank"}, length: { maximum: 50, too_long: "%{count} caracteres es el máximo permitido"}
	validates :description, presence: {message: "can't be blank"}, length: { maximum: 50, too_long: "%{count} caracteres es el máximo permitido"}
	validates :status, presence: {message: "can't be blank"}, length: { maximum: 50, too_long: "%{count} caracteres es el máximo permitido"}

	def check_users_subject
		puts 'Entre'
		puts 'modelo: '+self.users.count.to_s
		status = self.status.to_s
		if self.users.count == 0
			return 1
		else 
			return 0
		end
	end
end	

app/controllers/admin/subjects_controller.rb
class Admin::SubjectsController < Admin::AdminController
  before_action :set_subject, only: [:show, :edit, :update, :destroy]

  # GET /subjects
  # GET /subjects.json
  def index
    authorize! :read, Subject
    if params[:status]
      @subjects = Subject.where(status: params[:status])
      @profesor_subject = ProfesorSubject.all
      @users = User.where(id: ProfesorSubject.all.pluck(:user_id)).where(id: Role.find_by_name("Profesor").users.pluck(:user_id))
    else
      @subjects = Subject.all
      @profesor_subject = ProfesorSubject.all
      @users = User.where(id: ProfesorSubject.all.pluck(:user_id)).where(id: Role.find_by_name("Profesor").users.pluck(:user_id))
    end    
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
    authorize! :read, Subject
    @profesor_subject = Subject.find(@subject.id).users
  end

  # GET /subjects/new
  def new
    authorize! :create, Subject
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit
    authorize! :update, Subject
    @users_section = Subject.find(@subject.id).users
    @users = User.where(status: 'Activo').where.not(id: ProfesorSubject.all.pluck(:user_id)).where(id: Role.find_by_name("Profesor").users.pluck(:user_id)) - Subject.find(@subject.id).users
  end

  # POST /subjects
  # POST /subjects.json
  def create
    authorize! :create, Subject
    @subject = Subject.new(subject_params)

    if @subject.save
      flash[:success] = "Materia ha sido creada exitosamente"
      redirect_to admin_subjects_path(status: @subject.status)
    else
      flash[:danger] = "Materia no creada"
      redirect_to new_admin_subjects_path
    end
  end

  # PATCH/PUT /subjects/1
  def update
    authorize! :update, Subject
    begin
      if @subject.update(subject_params)
        flash[:success] = "Materia modificada exitosamente"
        redirect_to admin_subjects_path(status: @subject.status)
      else
        flash[:danger] = "Materia no modificada, por favor revise los campos"
        render 'edit'
      end
    rescue ActiveRecord::InvalidForeignKey
      flash[:danger] = "Materia no modificada, existen registros asociados al registro que esta tratando de modificar"
      redirect_to admin_subjects_path(status: @subject.status)
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    authorize! :destroy, Subject
    if @subject.check_users_subject == 1
      begin
        @subject.destroy
        flash[:danger] = "Materia eliminada del sistema"
        redirect_to admin_subjects_path(status: @subject.status)
      rescue ActiveRecord::InvalidForeignKey
        flash[:danger] = "Materia no eliminada, existen registros asociados al registro que esta tratando de modificar"
        redirect_to admin_subjects_path(status: @subject.status)
      end
    else
      flash[:warning] = "Materia no eliminada del sistema, existen registros asociados"
      redirect_to admin_subjects_path(status: @subject.status)
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      if Subject.is_numeric(params[:id]) == true
        begin
          @subject = Subject.find(params[:id])
        rescue Exception => e
          puts "Exception: "+e.to_s
          flash[:warning] = "Ocurrió un error en el sistema"
          redirect_to admin_subjects_path(status: 'Activo')
        end
      else
        redirect_to admin_subjects_path(status: 'Activo')
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_params
      params.require(:subject).permit(:name, :description, :status, user_ids: [])
    end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/admin/subjects/_form.html.erb
<%= form_with(model: subject, url: url, local: true) do |f| %>

	<div class="form-group row">
    <div class="col-sm-6 mb-3 mb-sm-0">
      <!-- <input type="text" class="form-control form-control-user" id="exampleFirstName" placeholder="First Name"> -->
      <label>Nombre</label>
      <%= f.text_field :name, class:'form-control form-control-user', id:"exampleName", placeholder:"Name", autofocus: true, autocomplete: "name", required: "required"%>
    </div>
  </div>

	<div class="form-group">
    <!-- <input type="text" class="form-control form-control-user" id="exampleLastName" placeholder="Last Name"> -->
    	<label>Descripcion</label>
      <%= f.text_area :description, class:'form-control form-control-user', id:"exampledescription", placeholder:"Descripcion", autofocus: true, autocomplete: "description", cols: "15", rows:"4", required: "required" %>
  </div>

  <div class="form-group">
    <!-- <input type="text" class="form-control form-control-user" id="exampleLastName" placeholder="Last Name"> -->
      <label>Status</label>
      <%= select_tag "subject[status]", options_for_select([['Seleccione Status', nil], ['Activo', 'Activo'], ['Inactivo', 'Inactivo']], selected: @subject.status ), class: 'browser-default custom-select', id: "status_picker", required: "required"%>
  </div>

	<br>

  <div class="row">
      <div class="col-lg-6 col-md-6 col-xs-12">
        <!-- <div class="card shadow mb-4"> -->
          <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-dark">Profesores</h6>
          </div>
          <!-- <div class="card-body"> -->
              <table class="table table-striped table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                  <tr>
                    <!-- <th>Correo</th> -->
                    <th>Nombre</th>
                    <th>ID</th>
                    <th>Accion</th>
                  </tr>
                </thead>
                <tfoot>
                  <tr>
                    <!-- <th>Correo</th> -->
                    <th>Nombre</th>
                    <th>ID</th>
                    <th>Accion</th>
                  </tr>
                </tfoot>
                <tbody>

                </tbody>
              </table>
          <!-- </div> -->
        <!-- </div> -->
      </div>

      <div class="col-lg-6 col-md-6 col-xs-12">
        <!-- <div class="card shadow mb-4"> -->
          <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-dark">Materia</h6>
          </div>
          <!-- <div class="card-body"> -->
              <table class="table table-striped table-bordered" id="dataTable2" width="100%" cellspacing="0">
                <thead>
                  <tr>
                    <!-- <th>Correo</th> -->
                    <th>Nombre</th>
                    <th>ID</th>
                    <th>Accion</th>
                  </tr>
                </thead>
                <tfoot>
                  <tr>
                    <!-- <th>Correo</th> -->
                    <th>Nombre</th>
                    <th>ID</th>
                    <th>Accion</th>
                  </tr>
                </tfoot>
                <tbody>

                </tbody>
              </table>
            <!-- </div> -->
        <!-- </div> -->
      </div>
    </div>
  
    <hr>

    <div class="form-group row">
      <div class="col-sm-6 mb-3 mb-sm-0">
        
        <% if @subject.id %>
          <% if can? :update, Subject %>
              <%= f.submit "Editar", class:'btn btn-primary btn-sm' %>
          <% end %>

          <% if can? :read, Subject and  @subject.id %>
            <%= link_to "Ver" , admin_subject_path(@subject), :class => 'btn btn-sm btn-warning shadow-sm' %>
          <% end %>
        <% else %>
          <% if can? :create, Subject %>
            <%= f.submit "Crear", class:'btn btn-primary btn-sm shadow-sm' %>
          <% end %>
        <% end %>
        <% if can? :read, Subject %>
            <%= link_to 'Cancel', url_for(:back), :class => 'btn btn-sm btn-light shadow-sm' %>
        <% end %>
        
        <br>
      </div>
    </div>
<% end %>

app/views/admin/subjects/edit.html.erb
<div class="d-sm-flex align-items-center justify-content-between mb-4">
  <h1 class="h3 mb-0 text-gray-800">Editar Materia</h1>
</div>

<%= render 'form', subject: @subject, url: admin_subject_path(@subject) %>

<script type="text/javascript">
    
    var idUsers = [];

  function addUser(id, name, lastname, dni, iddataTable)
  {
      //var $dataTable = $('#dataTable2').dataTable();
      //alert(id + name + lastname + dni + iddataTable);

      lastname = (lastname)?lastname:'';

      if (iddataTable == 1)
      {
        var dataTable = $('#dataTable2').dataTable();
        dni = !(dni)?'No id':dni;
        dataTable.fnAddData([
          (name)+' '+(lastname),
          dni+""+'<input type="hidden" readonly="readonly" value="'+id+'" id="inputValue'+id+'">',
          ""+'<button class="btn-floating btn-sm btn-outline-danger" id="accionValuedt2'+id+'" data-toggle="tooltip" data-placement="botton" title="Remover Estudiante">-</button>'
        ]);
      } else
      {
        var dataTable = $('#dataTable').dataTable();
        dni = !(dni)?'No id':dni;
        dataTable.fnAddData([
          (name)+' '+(lastname),
          dni+""+'<input type="hidden" readonly="readonly" value="'+id+'" id="inputValue'+id+'">',
          ""+'<button class="btn-floating btn-sm btn-outline-success" id="accionValuedt2'+id+'" data-toggle="tooltip" data-placement="botton" title="Agregar a Seccion">+</button>'
        ]);
      }
    }
  
  <% @users_section.each do |us| %>
    $(document).ready(function(){
        var dataTable = $('#dataTable2').dataTable();
        dataTable.fnAddData([
          ('<%= us.name %>')+' '+('<%= us.lastname %>'),
              '<%= us.dni %>'+""+'<input type="hidden" readonly="readonly" value="<%= us.id %>" id="inputValue<%= us.id %>">',
              ""+'<button class="btn-floating btn-sm btn-outline-danger" id="accionValuedt2<%= us.id %>'+'"  data-toggle="tooltip" data-placement="botton" title="Remover Estudiante">-</button>'
      ]);
    });      
    <% end %>

    <% @users.each do |user| %>
      $(document).ready(function(){
        var dataTable = $('#dataTable').dataTable();
        dataTable.fnAddData([
          ('<%= user.name %>')+' '+('<%= user.lastname %>'),
              '<%= user.dni %>'+""+'<input type="hidden" readonly="readonly" value="<%= user.id %>" id="inputValue<%= user.id %>">',
              ""+'<button class="btn-floating btn-sm btn-outline-success" id="accionValuedt1<%= user.id %>" data-toggle="tooltip" data-placement="botton" title="Agregar a Seccion">+</button>'
      ]);
    }); 
    <% end %>

    function getTableData(){
      data = [];
      $( ".hello" ).remove();
      $("#dataTable2 td:nth-child(2)").each(function (index) {
          var row = 'Row no. ' + (index+1) + ', Column 2 : ' + $(this).html();
          var id = (row.split('value="')[1]).split('"')[0];
          data.push(id);

          $('<input>').attr({class:"hello", id: id, name: "subject[user_ids][]", type:'hidden', value: id}).appendTo("form");  
      });
      return data;
  }

    $(document).ready(function(){
    var table = $('#dataTable2').DataTable();
    $('#dataTable2').on( 'click', 'button', function () {
      var id, name, lastname, dni;
      for (i = 0; i < ((table.row( $(this).parents('tr') ).data()).length - 1); i++)
      {
        if (i == 0){
          name = table.row( $(this).parents('tr') ).data()[i];
          lastname = '';
        } else if(i == 1){
          dni = (table.row( $(this).parents('tr') ).data())[i].split("<")[0];
          id = ((table.row( $(this).parents('tr') ).data())[i].split('value="')[1]).split('"')[0];    
        } 
      }
      
      table.row( $(this).parents('tr') ).remove().draw(false);
      addUser(id, name, lastname, dni, 2);
      idUsers = getTableData();
    }); 
  });

  $(document).ready(function(){
    var table = $('#dataTable').DataTable();
    $('#dataTable').on( 'click', 'button', function () {

      console.log( table.row( $(this).parents('tr') ).data() );
      
      var id, name, lastname, dni;
      for (i = 0; i < ((table.row( $(this).parents('tr') ).data()).length - 1); i++)
      {
        if (i == 0){
          name = table.row( $(this).parents('tr') ).data()[i];
          lastname = '';
        } else if(i == 1){
          dni = (table.row( $(this).parents('tr') ).data())[i].split("<")[0];
          id = ((table.row( $(this).parents('tr') ).data())[i].split('value="')[1]).split('"')[0];    
        } 
      }
      
      //table.row( this ).delete();
      table.row( $(this).parents('tr') ).remove().draw(false);
      addUser(id, name, lastname, dni, 1);
      idUsers = getTableData();
    }); 
  });

</script>

app/views/admin/subjects/index.html.erb
  <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-2 text-gray-800">Materias <% if params[:status] == 'Inactivo' %> Inactivas <% elsif params[:status] == 'Activo' %> Activas <% else %>  <%end%></h1>
    <% if can? :create, Subject %>
      <a href="<%= new_admin_subject_path  %>" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fa fa-plus fa-sm text-white-50"></i> Crear Materia</a>
    <%end%>
  </div>

  <%= render 'admin/home/messages' if !flash.empty? %>

  <!-- DataTales Example -->
  <div class="col-lg-12 col-md-12 col-xs-12">
    <table class="table table-striped table-responsive-md btn-table table-bordered" id="dataTable" width="100%" cellspacing="0">
      <thead>
        <tr>
          <th><center>Nombre</center></th>
          <th class="d-none d-sm-table-cell"><center>Descripcion</center></th>
          <th width="275" class="d-none d-sm-table-cell"><center>Profesores</center></th>
          <th width="225"><center>Acciones</center></th>
        </tr>
      </thead>
      <tfoot>
        <tr>
          <th><center>Nombre</center></th>
          <th class="d-none d-sm-table-cell"><center>Descripcion</center></th>
          <th width="275" class="d-none d-sm-table-cell"><center>Profesores</center></th>
          <th width="225"><center>Acciones</center></th>
        </tr>
      </tfoot>
      <tbody>
        <% @subjects.each do |subject| %>
          <tr>
            <td><center><%= subject.name %></center></td>
            <td class="d-none d-sm-table-cell"><center><%= truncate(subject.description , :length => 50) %></center></td>
            <td class="d-none d-sm-table-cell">
              <center>
                <select name="" id="" class="browser-default custom-select">
                    <option value="" selected="true">Profesores: <%= subject.name %> </option>
                  <% subject.users.ids.each do |ps| %>
                    <option value=""><%= User.find(ps).name+' '+User.find(ps).lastname %></option>
                  <% end %>
                </select>
              </center>
            </td>
            <td>
              <center>
                <% if can? :update, Subject %>
                  <a href="<%= admin_subject_path(subject)%>"><button class="btn-floating btn-sm btn-outline-info shadow-sm" data-placement="botton" title="Detalle <%= subject.name %> "><i class="fas fa-fw fa-eye"></i></button></a>
                <% end %>
                <% if can? :update, Subject %>
                  <a href="<%=edit_admin_subject_path(subject)%>"><button class="btn-floating btn-sm btn-outline-primary shadow-sm" data-placement="botton" title="Editar <%= subject.name %>"><i class="fas fa-fw fa-edit"></i></button></a>
                <% end %>
                <% if can? :destroy, Subject %>
                   <button class="btn-floating btn-sm btn-outline-danger shadow-sm" href="#"  data-placement="botton" title="Eliminar <%= subject.name %>" onclick="check_and_display_delete_modal('<%= subject.id %>', 'Esta seguro de Eliminar la Materia <%= subject.name %>', 'Eliminar Materia?')"><i class="fas fa-fw fa-trash"></i></button>
                <%end%>
              </center>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <!-- Logout Modal-->
  <div class="modal fade" id="DeleteSubject" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Eliminar Materia?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">
          

        </div>
        <div class="modal-footer" id="myModalFooter">
          <button class="d-none d-sm-inline-block btn btn-sm btn-light shadow-sm" type="button" data-dismiss="modal">Cancel</button>
          <!-- <a class="btn btn-primary" href="login.html">Logout</a> -->
          <!-- <a class="d-none d-sm-inline-block btn btn-sm btn-danger shadow-sm" rel="nofollow" data-method="delete" href="/admin/sections/26">Eliminar</a> -->

          </div>
      </div>
    </div>
  </div>



<script type="text/javascript">
  
  $(document).ready(function () {
    $('#dataTable').DataTable();
    $('.dataTables_length').addClass('bs-select');
  });

  <% len = @subjects.length %>
  var subjects = {
    <% @subjects.each_with_index do |subject, index| %>
      
      <% if index+1 != len %>
        '<%= subject.id %>' : '<%=link_to('Eliminar Materia', admin_subject_path(subject), class:'btn btn-danger btn-sm shadow-sm modal_delete', method: :delete) %>',
      <% elsif index+1 == len %>
        '<%= subject.id %>' : '<%= link_to('Eliminar Materia', admin_subject_path(subject), class:'btn btn-danger btn-sm shadow-sm modal_delete', method: :delete) %>'
      <%  end %>
    <% end %>
  };

  

  function check_and_display_delete_modal(id, menssage, modal_title){

    $('.modal_delete').remove();
    
    button = subjects[id];

    console.log(button);

    $modal = $('#DeleteSubject');
    $modal.find('.modal-title').text('' + modal_title);
    $modal.find('.modal-body').text(''+ menssage);

    //$(".d-none.d-sm-inline-block.btn.btn-sm.btn-danger.shadow-sm").remove(); //Con esta linea elimino en el modal un button parecido al que realizara la accion de eliminar.
    
    $( "#myModalFooter" ).append(button);
    $modal.modal('show');
  }

</script>

app/views/admin/subjects/new.html.erb
<div class="d-sm-flex align-items-center justify-content-between mb-4">
	<h1 class="h3 mb-0 text-gray-800">Crear Materia</h1>
</div>

<%= render 'form', subject: @subject, url: admin_subjects_path(@subject) %>

<script type="text/javascript">

  var idUsers = [];

  function addUser(id, name, lastname, dni, iddataTable)
  {
    //var $dataTable = $('#dataTable2').dataTable();
    //alert(id + name + lastname + dni + iddataTable);

    lastname = (lastname)?lastname:'';

    if (iddataTable == 1)
    {
      var dataTable = $('#dataTable2').dataTable();
      dni = !(dni)?'No id':dni;
      dataTable.fnAddData([
        (name)+' '+(lastname),
        dni+""+'<input type="hidden" readonly="readonly" value="'+id+'" id="inputValue'+id+'">',
        ""+'<button class="btn-floating btn-sm btn-outline-danger" id="accionValuedt2'+id+'" data-toggle="tooltip" data-placement="botton" title="Remover Estudiante">-</button>'
      ]);
    } else
    {
      var dataTable = $('#dataTable').dataTable();
      dni = !(dni)?'No id':dni;
      dataTable.fnAddData([
        (name)+' '+(lastname),
        dni+""+'<input type="hidden" readonly="readonly" value="'+id+'" id="inputValue'+id+'">',
        ""+'<button class="btn-floating btn-sm btn-outline-success" id="accionValuedt2'+id+'" data-toggle="tooltip" data-placement="botton" title="Agregar a Seccion">+</button>'
      ]);
    }
  }

  function getTableData(){
    data = [];
    $( ".hello" ).remove();
    $("#dataTable2 td:nth-child(2)").each(function (index) {
      var row = 'Row no. ' + (index+1) + ', Column 2 : ' + $(this).html();
      var id = (row.split('value="')[1]).split('"')[0];
      data.push(id);

      $('<input>').attr({class:"hello", id: id, name: "subject[user_ids][]", type:'hidden', value: id}).appendTo("form");  
    }
    );
    return data;
  }

  $(document).ready(function(){
    var dataTable = $('#dataTable').dataTable();
    $('.dataTables_length').addClass('bs-select');
    var data = $.getJSON('<%= admin_users_path(:role => 'Profesor', :status => 'Activo') %>',function(data){
      $.each(data, function(idx, elem){

        elem.dni = !(elem.dni)?'No id':elem.dni;

        dataTable.fnAddData([
          //elem.email+"",
          (elem.name)+' '+(elem.lastname),
          elem.dni+""+'<input type="hidden" readonly="readonly" value="'+elem.id+'" id="inputValue'+elem.id+'">',
          ""+'<button href="#/" class="btn-floating btn-sm btn-outline-success" id="accionValuedt1'+elem.id+'" data-toggle="tooltip" data-placement="botton" title="Agregar a Seccion">+</button>' 
        ]);
      });
    });
  }); 

  $(document).ready(function(){
    var table = $('#dataTable2').DataTable();
    $('.dataTables_length').addClass('bs-select');
    $('#dataTable2').on( 'click', 'button', function () {
      var id, name, lastname, dni;
      for (i = 0; i < ((table.row( $(this).parents('tr') ).data()).length - 1); i++)
      {
        if (i == 0){
          name = table.row( $(this).parents('tr') ).data()[i];
          lastname = '';
        } else if(i == 1){
          dni = (table.row( $(this).parents('tr') ).data())[i].split("<")[0];
          id = ((table.row( $(this).parents('tr') ).data())[i].split('value="')[1]).split('"')[0];    
        } 
      }
      
      table.row( $(this).parents('tr') ).remove().draw(false);
      addUser(id, name, lastname, dni, 2);
      idUsers = getTableData();
    }); 
  });

  $(document).ready(function(){
    var table = $('#dataTable').DataTable();
    $('.dataTables_length').addClass('bs-select');
    $('#dataTable').on( 'click', 'button', function () {

      console.log( table.row( $(this).parents('tr') ).data() );
      
      var id, name, lastname, dni;
      for (i = 0; i < ((table.row( $(this).parents('tr') ).data()).length - 1); i++)
      {
        if (i == 0){
          name = table.row( $(this).parents('tr') ).data()[i];
          lastname = '';
        } else if(i == 1){
          dni = (table.row( $(this).parents('tr') ).data())[i].split("<")[0];
          id = ((table.row( $(this).parents('tr') ).data())[i].split('value="')[1]).split('"')[0];    
        } 
      }
      
      //table.row( this ).delete();
      table.row( $(this).parents('tr') ).remove().draw(false);
      addUser(id, name, lastname, dni, 1);
      idUsers = getTableData();
    }); 
  });
</script>

app/views/admin/subjects/show.html.erb
<div class="d-sm-flex align-items-center justify-content-between mb-4">
	<h1 class="h3 mb-0 text-gray-800">Materia: <%= @subject.name %></h1>
</div>

<div class="row">
	<div class="col-lg-12">

		<!-- Collapsable Card Example -->
		<div class="card shadow mb-4">
		<!-- Card Header - Accordion -->
			<a href="#collapseCardExample1" class="d-block card-header py-3" data-toggle="collapse" role="button" aria-expanded="true" aria-controls="collapseCardExample1">
				<h6 class="m-0 font-weight-bold text-dark">Descripcion</h6>
			</a>
			<!-- Card Content - Collapse -->
			<div class="collapse show" id="collapseCardExample1">
				<div class="card-body">
				<strong><%= @subject.description%>.</strong>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-lg-12 col-md-12 col-xs-12">

		<!-- Collapsable Card Example -->
		<!-- <div class="card shadow mb-4"> -->
		<!-- Card Header - Accordion -->
			<a href="#collapseCardExample2" class="d-block card-header py-3" data-toggle="collapse" role="button" aria-expanded="true" aria-controls="collapseCardExample2">
				<h6 class="m-0 font-weight-bold text-dark">Profesores</h6>
			</a>
			<!-- Card Content - Collapse -->
			<div class="collapse show" id="collapseCardExample2">
				<!-- <div class="card-body"> -->
				<strong>
					<!-- <div class="card-body"> -->
			            <table class="table table-striped table-bordered" id="dataTable" width="100%" cellspacing="0">
			              <thead>
			                <tr>
			                  <th><center>Correo</center></th>
			                  <th><center>Nombre</center></th>
			                  <th><center>ID</center></th>
			                </tr>
			              </thead>
			              <tfoot>
			                <tr>
			                  <th><center>Correo</center></th>
			                  <th><center>Nombre</center></th>
			                  <th><center>ID</center></th>
			                </tr>
			              </tfoot>
			              <tbody>
			              	<% @profesor_subject.each do |us| %>
				              	<tr>
				              		<td><center><%= us.email %></center></td>
				              		<td><center><%= us.name %> <%= us.lastname %></center></td>
				              		<td><center><%= us.dni %></center></td>
				              	</tr>
			              	<% end %>
			              </tbody>
			            </table>
			        <!-- </div> -->
				</strong>
				<!-- </div> -->
			</div>
		<!-- </div> -->
	</div>
</div>




<div class="form-group">
	<hr>
    <div class="col-lg-12 col-md-12 col-xs-12">
    	<% if can? :update, Subject %>
			<%= link_to 'Editar', edit_admin_subject_path(@subject), :class => 'btn btn-sm btn-primary shadow-sm' %>
		<% end %>

		<% if can? :read, Subject %>
			<%= link_to 'Atras', url_for(:back), :class => 'btn btn-sm btn-light shadow-sm' %>
		<% end %>
	</div>
</div>


<script>

	$(document).ready(function () {
	    $('#dataTable').DataTable();
	    //$('.dataTables_length').addClass('bs-select');


	});

	
</script>