config/routes.rb
Rails.application.routes.draw do

  # Root page
  root 'home#index'

  # Foros y comentarios
  # resources :sections do
  #   resources :forums do
  #     resources :coments
  #   end
  # end

  # Foros 
  resources :forums do
    resources :comments
  end

  # Ads (anuncios)
  resources :ads

  # Archivos y calificaciones
  resources :archives

  resources :alumnos
  resources :personals
   
  get '/return_tought' => 'home#return_tought', :as => :return_tought

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions:      'users/sessions'
  }

  devise_scope :user do
    get 'access',        to: 'users/registrations#access'
    put 'access_update', to: 'users/registrations#access_update'
  end

  namespace :admin do
    resources :news, only:[:index, :new, :create, :edit, :update, :destroy]
    resources :subjects
    resources :users, only:[:index, :new, :create, :edit, :update, :destroy]
    resources :sections
    resources :thoughts, only:[:index, :new, :create, :edit, :update, :destroy]
    resources :emails, only:[:index, :destroy]
    get "students_users_with_not_section" => "sections#students_users_with_not_section", :as => :students_users_with_not_section
    get "professors_with_subjects" => "sections#professors_with_subjects", :as => :professors_with_subjects
    get "section_professor_consult/:id" => "sections#section_professor_consult", :as => :section_professor_consult
    patch  "reset_password/:id" => "users#reset_password", :as => :reset_password
    get "send_email_representing" => "users#send_email_representing", :as => :send_email_representing
    get "send_mm_email" => "users#send_mm_email", :as => :send_mm_email
    get "send_ms_email" => "users#send_ms_email", :as => :send_ms_email
    get "check_mode" => "admin#check_mode", :as => :check_mode
    get "update_mode" => "admin#update_mode", :as => :update_mode
  end

  
  # devise_for :users
  # get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  match '*path' => 'application#error_redirect', via: :all
end

app/models/thought.rb
class Thought < ApplicationRecord
	validates :author, presence: {message: "Autor no puede estar vacío"}, length: { maximum: 50, too_long: "%{count} caracteres es el máximo permitido"}
	validates :thought, presence: {message: "Pensamiento no puede estar vacío"}, length: { maximum: 350, too_long: "%{count} caracteres es el máximo permitido"}
end

app/controllers/admin/thoughts_controller.rb
class Admin::ThoughtsController < Admin::AdminController
  before_action :set_thought, only: [:show, :edit, :update, :destroy]

  # GET /thoughts
  # GET /thoughts.json
  def index
    authorize! :read, Thought
    if params[:status] == 'true'
      @thoughts = Thought.limit(1).order("RANDOM()")     
    else
      @thoughts = Thought.all
    end 
    
  end

  # GET /thoughts/1
  # GET /thoughts/1.json
  def show
    authorize! :read, Thought
  end

  # GET /thoughts/new
  def new
    authorize! :create, Thought
    @thought = Thought.new
  end

  # GET /thoughts/1/edit
  def edit
    authorize! :update, Thought
  end

  # POST /thoughts
  # POST /thoughts.json
  def create
    authorize! :create, Thought
    @thought = Thought.new(thought_params)

    if @thought.save
      flash[:success] = "Pensamiento ha sido creado exitosamente"
      redirect_to admin_thoughts_path
    else
      flash.now[:danger] = "Pensamiento no creado"
      redirect_to new_admin_thoughts_path
    end
  end

  # PATCH/PUT /thoughts/1
  # PATCH/PUT /thoughts/1.json
  def update
    authorize! :update, Thought
    if @thought.update(thought_params)
      flash[:success] = "Pensamiento modificado exitosamente"
      redirect_to admin_thoughts_path
    else
      flash.now[:danger] = "Pensamiento no modificado, por favor revise los campos"
      render 'edit'
    end
  end

  # DELETE /thoughts/1
  # DELETE /thoughts/1.json
  def destroy
    authorize! :destroy, Thought
    @thought.destroy
    flash[:danger] = "Pensamiento eliminado del sistema"
    redirect_to admin_thoughts_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thought
      begin
        @thought = Thought.find(params[:id])
      rescue Exception => e
        puts "Exception: "+e.to_s
        flash[:warning] = "Ocurrió un error en el sistema"
        redirect_to admin_thoughts_path
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def thought_params
      params.require(:thought).permit(:thought, :author)
    end
end

app/helpers/thoughts_helper.rb
module ThoughtsHelper
end

app/views/admin/thoughts/_form.html.erb
<%= form_with(model: thought, url: url, local: true) do |f| %>

	<%= render 'admin/home/messages' if !flash.empty? %>
 	
	<div class="form-group row">
	    <div class="col-sm-6 mb-3 mb-sm-0">
	      <!-- <input type="text" class="form-control form-control-user" id="exampleFirstName" placeholder="First Name"> -->
	     	<label>Autor</label>
	      	<%= f.text_field :author, class:'form-control', id:"exampleauthor", placeholder:"Autor", autofocus: true, autocomplete: "author", required:'true'%>
	    </div>
	</div>

	<div class="form-group">
	    <!-- <input type="text" class="form-control form-control-user" id="exampleLastName" placeholder="Last Name"> -->
		<label>Descripcion</label>
	    <%= f.text_area :thought, class:'form-control form-control-user', id:"thought", placeholder:"Pensamiento", autofocus: true, autocomplete: "thought", cols: "15", rows:"4", required:'true'%>
	</div>

  	<hr>
	
	<div class="form-group row">
		<div class="col-sm-6 mb-3 mb-sm-0">
			
			<% if @thought.id %>
				<% if can? :update, Thought %>
		    		<%= f.submit "Editar", class:'btn btn-primary btn-sm' %>
				<% end %>
			<% else %>
				<% if can? :create, Thought %>
					<%= f.submit "Crear", class:'btn btn-primary btn-sm shadow-sm' %>
				<% end %>
			<% end %>
			<% if can? :read, Thought %>
		    	<%= link_to 'Cancel', url_for(:back), :class => 'btn btn-sm btn-light shadow-sm' %>
		    <% end %>
		    <br>
		</div>
	</div>
<% end %>

app/views/admin/thoughts/edit.html.erb
<div class="d-sm-flex align-items-center justify-content-between mb-4">
	<h1 class="h3 mb-0 text-gray-800">Editar Pensamiento</h1>
</div>

<%= render 'form', thought: @thought, url: admin_thought_path(@thought) %>

app/views/admin/thoughts/index.html.erb
  <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-2 text-gray-800">Pensamientos</h1>
    <% if can? :create, Thought %>
      <a href="<%= new_admin_thought_path  %>" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fa fa-plus fa-sm text-white-50"></i> Crear Pensamiento</a>
    <%end%>
    <!-- <a href="<%= new_admin_news_path  %>"><button class="btn btn-primary btn-sm"><i class="fa fa-plus fa-sm text-white-50"></i> Crear Anuncio</button></a> -->
  </div>

  <%= render 'admin/home/messages' if !flash.empty? %>
    
  <!-- DataTales Example -->
  <div class="col-lg-12 col-md-12 col-xs-12">
    <!-- <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">DataTables Example</h6>
    </div> -->
    <div class="card-body">
        <table class="table table-striped table-responsive-md btn-table table-bordered" id="dataTable" width="100%" cellspacing="0">
          <thead>
            <tr>
              <th><center>Pensamiento</center></th>
              <th width="215"><center>Autor</center></th>
              <th width="225"><center>Acciones</center></th>
            </tr>
          </thead>
          <tfoot>
            <tr>
              <th><center>Descripcion</center></th>
              <th width="215"><center>Autor</center></th>
              <th width="225"><center>Acciones</center></th>
            </tr>
          </tfoot>
          <tbody>
            <% @thoughts.each do |thought| %>
              <tr>
                <td><center><%= thought.thought %></center></td>
                <td>
                  <center><%= thought.author %></center>
                </td>
                <td>
                  <center>
                    <% if can? :read, Thought %>
                      <!-- <a href="<%#= admin_thought_path(thought)%>"><button class="btn-floating btn-sm btn-outline-info shadow-sm" data-toggle="tooltip" data-placement="botton" title="Detalle <%#= thought.thought %>"><i class="fas fa-fw fa-eye"></i></button></a> -->

                      <a href="#"><button class="btn-floating btn-sm btn-outline-info shadow-sm" onclick="set_detail_thought('<%= thought.id%>', '<%= thought.thought %>','<%= thought.author %>', '<%= edit_admin_thought_path(thought) %>')" data-toggle="tooltip" data-placement="botton" title="Detalle <%= thought.thought %>"><i class="fas fa-fw fa-eye"></i></button></a>

                    <% end %>

                    <% if can? :update, Thought %>
                      <a href="<%=edit_admin_thought_path(thought)%>"><button class="btn-floating btn-sm btn-outline-primary shadow-sm" data-toggle="tooltip" data-placement="botton" title="Editar <%= thought.thought %>"><i class="fas fa-fw fa-edit"></i></button></a>
                    <% end %>
                    
                    
                    <% if can? :destroy, Thought %>
                      <button class="btn-floating btn-sm btn-outline-danger shadow-sm" href="#"  data-placement="botton" title="Eliminar <%= thought.thought %>" onclick="check_and_display_delete_modal('<%= thought.id %>', 'Esta seguro de Eliminar el Pesamiento <%= thought.thought %>', 'Eliminar Pensamiento?')"><i class="fas fa-fw fa-trash"></i></button>
                    <%end%>
                  </center>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
    </div>
  </div>


  <!-- Logout Modal-->
  <div class="modal fade" id="DeleteThought" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Eliminar Pensamiento?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">
          

          </div>
        <div class="modal-footer" id="myModalFooter">
          <button class="d-none d-sm-inline-block btn btn-sm btn-light shadow-sm" type="button" data-dismiss="modal">Cancel</button>
          <!-- <a class="btn btn-primary" href="login.html">Logout</a> -->
          <!-- <a class="d-none d-sm-inline-block btn btn-sm btn-danger shadow-sm" rel="nofollow" data-method="delete" href="/admin/sections/26">Eliminar</a> -->

          </div>
      </div>
    </div>
  </div>




<script type="text/javascript">
  
  $(document).ready(function () {
    $('#dataTable').DataTable();
    $('.dataTables_length').addClass('bs-select');
  });

  <% len = @thoughts.length %>
  var thoughts = {
    <% @thoughts.each_with_index do |thought, index| %>
      
      <% if index+1 != len %>
        '<%= thought.id %>' : '<%=link_to('Eliminar Pensamiento', admin_thought_path(thought), class:'btn btn-danger btn-sm shadow-sm modal_delete', method: :delete) %>',
      <% elsif index+1 == len %>
        '<%= thought.id %>' : '<%= link_to('Eliminar Pensamineto', admin_thought_path(thought), class:'btn btn-danger btn-sm shadow-sm modal_delete', method: :delete) %>'
      <%  end %>
    <% end %>
  };

  function check_and_display_delete_modal(id, menssage, modal_title){

    $('.modal_delete').remove();
    
    button = thoughts[id];

    console.log(button);

    $modal = $('#DeleteThought');
    $modal.find('.modal-title').text('' + modal_title);
    $modal.find('.modal-body').text(''+ menssage);

    //$(".d-none.d-sm-inline-block.btn.btn-sm.btn-danger.shadow-sm").remove(); //Con esta linea elimino en el modal un button parecido al que realizara la accion de eliminar.
    
    $( "#myModalFooter" ).append(button);
    $modal.modal('show');
  }


  function set_detail_thought(id,thought,author,link_to_edit)
    {
      $('.modal_detail').remove();
      $('#ShowDetailModal').remove();

      id = id ? id : 'Sin identificar';
      thought = thought ? thought : 'Sin identificar';
      author = author ? author : 'Sin identificar';

      var modal = 
        '<!-- Logout Modal-->'+
        '<div class="modal fade modal_detail" id="ShowDetailModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">'+
          '<div class="modal-dialog modal-lg" role="document">'+
            '<div class="modal-content">'+
              '<div class="modal-header">'+
                '<h5 class="modal-title">Detalle Pensamineto: '+id+'</h5>'+
                '<button class="close" type="button" data-dismiss="modal" aria-label="Close">'+
                  '<span aria-hidden="true">×</span>'+
                '</button>'+
              '</div>'+

              '<div class="modal-body">'+
                
                '<div class="row">'+
                  '<div class="col-lg-12">'+
              
                    '<!-- Collapsable Card Example -->'+
                    '<div class="card shadow mb-4">'+
                    '<!-- Card Header - Accordion -->'+
                      '<a href="#collapseCardExample1" class="d-block card-header py-3" data-toggle="collapse" role="button" aria-expanded="true" aria-controls="collapseCardExample1">'+
                        '<h6 class="m-0 font-weight-bold text-dark">Autor</h6>'+
                      '</a>'+
                      '<!-- Card Content - Collapse -->'+
                      '<div class="collapse show" id="collapseCardExample1">'+
                        '<div class="card-body">'+
                          '<strong>'+author+'</strong>'+
                        '</div>'+
                      '</div>'+
                    '</div>'+

                    '<!-- Collapsable Card Example -->'+
                    '<div class="card shadow mb-4">'+
                    '<!-- Card Header - Accordion -->'+
                      '<a href="#collapseCardExample2" class="d-block card-header py-3" data-toggle="collapse" role="button" aria-expanded="true" aria-controls="collapseCardExample2">'+
                        '<h6 class="m-0 font-weight-bold text-dark">Pensamiento</h6>'+
                      '</a>'+
                      '<!-- Card Content - Collapse -->'+
                      '<div class="collapse show" id="collapseCardExample2">'+
                        '<div class="card-body">'+
                          '<strong>'+thought+'</strong>'+
                        '</div>'+
                      '</div>'+
                    '</div>'+

                  '</div>'+
                '</div>'+
                
              '</div>'+

              '<div class="modal-footer">'+
                '<a href="'+link_to_edit+'" > <button class="btn btn-primary btn-sm shadow-sm" type="button">Editar</button></a>'+
                '<button class="btn btn-success btn-sm shadow-sm" type="button" data-dismiss="modal">Aceptar</button>'+
              '</div>'+
            '</div>'+
          '</div>'+
        '</div>';

      //console.log(modal);

      $('body').append(modal);
      $modal = $('#ShowDetailModal');
      $modal.modal('show');

    }
  
</script>

app/views/admin/thoughts/new.html.erb
<div class="d-sm-flex align-items-center justify-content-between mb-4">
	<h1 class="h3 mb-0 text-gray-800">Crear Pensamiento</h1>
</div>

<%= render 'form', thought: @thought, url: admin_thoughts_path(@thought) %>

app/views/admin/thoughts/show.html.erb
<div class="d-sm-flex align-items-center justify-content-between mb-4">
	<h1 class="h3 mb-0 text-gray-800">Pensamiento: <%= @thought.id %></h1>
</div>

<div class="row">
	<div class="col-lg-12">

		<!-- Collapsable Card Example -->
		<div class="card shadow mb-4">
		<!-- Card Header - Accordion -->
			<a href="#collapseCardExample1" class="d-block card-header py-3" data-toggle="collapse" role="button" aria-expanded="true" aria-controls="collapseCardExample1">
				<h6 class="m-0 font-weight-bold text-dark">Pensamiento</h6>
			</a>
			<!-- Card Content - Collapse -->
			<div class="collapse show" id="collapseCardExample1">
				<div class="card-body">
				<strong><%= @thought.thought %></strong>
				</div>
			</div>
		</div>

		<!-- Collapsable Card Example -->
		<div class="card shadow mb-4">
		<!-- Card Header - Accordion -->
			<a href="#collapseCardExample2" class="d-block card-header py-3" data-toggle="collapse" role="button" aria-expanded="true" aria-controls="collapseCardExample2">
				<h6 class="m-0 font-weight-bold text-dark">Autor</h6>
			</a>
			<!-- Card Content - Collapse -->
			<div class="collapse show" id="collapseCardExample2">
				<div class="card-body">
				<strong><%= @thought.author %></strong>
				</div>
			</div>
		</div>
	</div>	
</div>	

<hr>

<div class="form-group">
    <div class="col-lg-12 col-md-12 col-xs-12">
		
		<% if can? :update, Thought %>
			<%= link_to 'Editar', edit_admin_thought_path(@thought), :class => 'd-none d-sm-inline-block btn btn-sm btn-primary shadow-sm' %>
		<% end %>

		<% if can? :read, Thought %>
			<%= link_to 'Atras', url_for(:back), :class => 'd-none d-sm-inline-block btn btn-sm btn-light shadow-sm' %>
		<% end %>
	</div>
</div>
	