config/routes.rb
Rails.application.routes.draw do

  # Root page
  root 'home#index'

  # Foros y comentarios
  # resources :sections do
  #   resources :forums do
  #     resources :coments
  #   end
  # end

  # Foros 
  resources :forums do
    resources :comments
  end

  # Ads (anuncios)
  resources :ads

  # Archivos y calificaciones
  resources :archives

  resources :alumnos
  resources :personals
   
  get '/return_tought' => 'home#return_tought', :as => :return_tought

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions:      'users/sessions'
  }

  devise_scope :user do
    get 'access',        to: 'users/registrations#access'
    put 'access_update', to: 'users/registrations#access_update'
  end

  namespace :admin do
    resources :news, only:[:index, :new, :create, :edit, :update, :destroy]
    resources :subjects
    resources :users, only:[:index, :new, :create, :edit, :update, :destroy]
    resources :sections
    resources :thoughts, only:[:index, :new, :create, :edit, :update, :destroy]
    resources :emails, only:[:index, :destroy]
    get "students_users_with_not_section" => "sections#students_users_with_not_section", :as => :students_users_with_not_section
    get "professors_with_subjects" => "sections#professors_with_subjects", :as => :professors_with_subjects
    get "section_professor_consult/:id" => "sections#section_professor_consult", :as => :section_professor_consult
    patch  "reset_password/:id" => "users#reset_password", :as => :reset_password
    get "send_email_representing" => "users#send_email_representing", :as => :send_email_representing
    get "send_mm_email" => "users#send_mm_email", :as => :send_mm_email
    get "send_ms_email" => "users#send_ms_email", :as => :send_ms_email
    get "check_mode" => "admin#check_mode", :as => :check_mode
    get "update_mode" => "admin#update_mode", :as => :update_mode
  end

  
  # devise_for :users
  # get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  match '*path' => 'application#error_redirect', via: :all
end

app/models/section.rb
class Section < ApplicationRecord
	#Users
	has_many :user_sections, dependent: :destroy
	has_many :users, through: :user_sections

	#Profesores y Materias
	has_many :section_profesor_subjects, dependent: :destroy
	has_many :profesor_subjects, through: :section_profesor_subjects

	# Foros
	has_many :forums, dependent: :destroy
	# Anuncios
	has_many :ads, dependent: :destroy
	# Archivos
	has_many :archives, dependent: :destroy

	validates :description, presence: { message: 'La seccion debe de tener una descripcion' }

	def to_s
		self.description    #pudiera colocar más información self.titulo+ “ | “ + self.contenio
	end

	def check_users_section
		puts 'Entre'
		puts 'modelo: '+self.users.count.to_s
		if self.users.count == 0 and self.profesor_subjects.count == 0
			return 1
		else 
			return 0
		end
	end
end

app/controllers/admin/sections_controller.rb
class Admin::SectionsController < Admin::AdminController
  before_action :set_section, only: [:show, :edit, :update, :destroy]

  # GET /sections
  # GET /sections.json
  def index
    authorize! :read, Section
    @sections = Section.all
    @users_section = UserSection.all
    @users = User.where(id: UserSection.all.pluck(:user_id)).where(id: Role.find_by_name("Estudiante").users.pluck(:user_id))
  end

  # GET /sections/1
  # GET /sections/1.json
  def show
    authorize! :read, Section
    @users_section = Section.find(@section.id).users
    @sps = SectionProfesorSubject.joins(profesor_subject: [:subject, :user]).select("section_profesor_subjects.*, subjects.name as sbname, users.name, users.lastname").where(:section_id => @section.id)
    # https://guides.rubyonrails.org/v5.1/active_record_querying.html#retrieving-specific-data-from-multiple-tables de aqui saque el query con ORM
  end

  def students_users_with_not_section
    authorize! :read, Section
    render :json => ( User.where.not(id: UserSection.all.pluck(:user_id)).where(id: Role.find_by_name("Estudiante").users.pluck(:user_id), status: 'Activo') )
  end

  def professors_with_subjects
    authorize! :read, Section
    #render :json => (Subject.select("subjects.name as subjectname, users.name as username, users.lastname as userlastname, profesor_subjects.id as idps").joins(:users))
    render :json => (Subject.select("subjects.name as subjectname, users.name as username, users.lastname as userlastname, users.dni as userdni, profesor_subjects.id as p_s_id ,profesor_subjects.*").joins(:users).where("subjects.status = ? ", "Activo")) 
  end

  def section_professor_consult
    authorize! :read, Section
    render :json => (SectionProfesorSubject.where(:profesor_subject_id => params[:id]))
  end

  # GET /sections/new
  def new
    authorize! :create, Section
    @students_users_with_not_section =  User.where.not(id: UserSection.all.pluck(:user_id)).where(id: Role.find_by_name("Estudiante").users.pluck(:user_id)) 
    @section = Section.new
    if @section.id
      @users_section = Section.find(@section.id).users
    else
      @users_section = nil
    end
  end

  # GET /sections/1/edit
  def edit
    authorize! :update, Section
    @users_section = Section.find(@section.id).users
    #@users = Role.find_by_name("Estudiante").users - Section.find(@section.id).users
    @sps = SectionProfesorSubject.joins(profesor_subject: [:subject, :user]).select("section_profesor_subjects.*, subjects.name as sbname, users.name, users.lastname").where(:section_id => @section.id)
    @users = User.where.not(id: UserSection.all.pluck(:user_id)).where(id: Role.find_by_name("Estudiante").users.pluck(:user_id)) - Section.find(@section.id).users
  end

  # POST /sections
  # POST /sections.json
  def create
    authorize! :create, Section
    @section = Section.new(section_params)
    if params[:section_profesor_subjects]
      if @section.save

        $i
        @profesor_subject_id
        @day
        @time_init
        @time_end

        params[:section_profesor_subjects].each do |spsa|
          $i = spsa.split(',').length
          @profesor_subject_id = (spsa.split(',')[$i-$i]).to_i
          @day = (spsa.split(',')[$i - ($i - 1)]).to_s
          @time_init = (spsa.split(',')[$i - ($i - 2)]).to_f
          @time_end = (spsa.split(',')[$i - ($i - 3)]).to_f

          SectionProfesorSubject.create!(:profesor_subject_id => @profesor_subject_id, :section_id => @section.id, :day => @day, :time_init => @time_init, :time_end => @time_end)
        end

        flash[:success] = "Seccion Creada Exitosamente"
        redirect_to admin_sections_path
      else
        flash[:danger] = @section.errors.full_messages
        render :new
      end  
    else
      flash[:danger] = "No se encontraron materias para agregar a la seccion"
      render :new
    end  
  end

  # PATCH/PUT /sections/1
  # PATCH/PUT /sections/1.json
  def update
    authorize! :update, Section
    #respond_to do |format|
    if params[:section_profesor_subjects]
      if @section.update(section_params)
        SectionProfesorSubject.where(:section_id => @section.id).destroy_all
        $i
        @profesor_subject_id
        @day
        @time_init
        @time_end

        params[:section_profesor_subjects].each do |spsa|
          $i = spsa.split(',').length
          @profesor_subject_id = (spsa.split(',')[$i-$i]).to_i
          @day = (spsa.split(',')[$i - ($i - 1)]).to_s
          @time_init = (spsa.split(',')[$i - ($i - 2)]).to_f
          @time_end = (spsa.split(',')[$i - ($i - 3)]).to_f
          SectionProfesorSubject.create!(:profesor_subject_id => @profesor_subject_id, :section_id => @section.id, :day => @day, :time_init => @time_init, :time_end => @time_end)
        end

        flash[:success] = "Seccion Editada Exitosamente"
        redirect_to admin_sections_path
        # format.html { redirect_to @section, notice: 'Section was successfully updated.' }
        # format.json { render :show, status: :ok, location: @section }
      else
        flash[:danger] = @section.errors.full_messages
        render :edit
        # format.html { render :edit }
        # format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    else
      flash[:danger] = "No se encontraron materias para agregar a la seccion"
      render :edit
    end
  end

  # DELETE /sections/1
  # DELETE /sections/1.json
  def destroy
    authorize! :destroy, Section
    if @section.check_users_section == 1  
      if @section.destroy
        SectionProfesorSubject.where(:section_id => @section.id).destroy_all
        redirect_to admin_sections_path
      else
        redirect_to admin_sections_path
      end
    else
      flash[:warning] = "Seccion no eliminada del sistema, existen registros asociados"
      redirect_to admin_sections_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section
      begin
        @section = Section.find(params[:id])
      rescue Exception => e
        puts "Exception: "+e.to_s
        flash[:warning] = "Ocurrió un error en el sistema"
        redirect_to admin_sections_path
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def section_params
      params.require(:section).permit(:description, user_ids: [])
    end
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/admin/sections/_form.html.erb
<%= form_with(model: section, url: url, local: true) do |f| %>
  	
  	<%= render 'admin/home/messages' if !flash.empty? %>

  	<div class="form-inputs">
  		<label>Nombre de la Sección</label>
  		<%= f.text_field :description, class:'form-control form-control-user', required:'true' %>	
	</div>

  	<br>

	<div class="row">
	    <div class="col-lg-6 col-md-6 col-xs-12">
	      <!-- <div class="card shadow mb-4"> -->
	        <div class="card-header py-3">
	          <h6 class="m-0 font-weight-bold text-dark">Estudiantes</h6>
	        </div>
	        <!-- <div class="card-body"> -->
	            <table class="table table-striped table-bordered" id="dataTable" width="100%" cellspacing="0">
	              <thead>
	                <tr>
	                  <!-- <th>Correo</th> -->
	                  <th>Nombre</th>
	                  <th>ID</th>
	                  <th>Accion</th>
	                </tr>
	              </thead>
	              <tfoot>
	                <tr>
	                  <!-- <th>Correo</th> -->
	                  <th>Nombre</th>
	                  <th>ID</th>
	                  <th>Accion</th>
	                </tr>
	              </tfoot>
	              <tbody>

	              </tbody>
	            </table>
	        <!-- </div> -->
	      <!-- </div> -->
	    </div>

	    <div class="col-lg-6 col-md-6 col-xs-12">
	      <!-- <div class="card shadow mb-4"> -->
	        <div class="card-header py-3">
	          <h6 class="m-0 font-weight-bold text-dark">Seccion</h6>
	        </div>
	        <!-- <div class="card-body"> -->
	            <table class="table table-striped table-bordered" id="dataTable2" width="100%" cellspacing="0">
	              <thead>
	                <tr>
	                  <!-- <th>Correo</th> -->
	                  <th>Nombre</th>
	                  <th>ID</th>
	                  <th>Accion</th>
	                </tr>
	              </thead>
	              <tfoot>
	                <tr>
	                  <!-- <th>Correo</th> -->
	                  <th>Nombre</th>
	                  <th>ID</th>
	                  <th>Accion</th>
	                </tr>
	              </tfoot>
	              <tbody>

	              </tbody>
	            </table>
	          <!-- </div> -->
	      <!-- </div> -->
	    </div>
  	</div>

  	<hr>

	<div class="row">
	    <div class="col-lg-12 col-md-12 col-xs-12">
	      <!-- <div class="card shadow mb-4"> -->
	        <div class="card-header py-3">
	          <h6 class="m-0 font-weight-bold text-dark">Materias</h6>
	        </div>
	        <!-- <div class="card-body"> -->
	            <table class="table table-striped table-bordered" id="dataTable3" width="100%" cellspacing="0">
	              <thead>
	                <tr>
	                  <!-- <th>Correo</th> -->
	                  <th>Materia</th>
	                  <th>Profesor</th>
	                  <th>Accion</th>
	                </tr>
	              </thead>
	              <tfoot>
	                <tr>
	                  <!-- <th>Correo</th> -->
	                  <th>Materia</th>
	                  <th>Profesor</th>
	                  <th>Accion</th>
	                </tr>
	              </tfoot>
	              <tbody>

	              </tbody>
	            </table>
	        <!-- </div> -->
	      <!-- </div> -->
	    </div>

	    <div class="col-lg-12 col-md-12 col-xs-12">
	      <!-- <div class="card shadow mb-4"> -->
	        <div class="card-header py-3">
	          <h6 class="m-0 font-weight-bold text-dark">Seccion</h6>
	        </div>
	        <!-- <div class="card-body"> -->
	            <table class="table table-striped table-bordered" id="dataTable4" width="100%" cellspacing="0">
	              <thead>
	                <tr>
	                  <!-- <th>Correo</th> -->
	                  <th>Materia</th>
	                  <th>Profesor</th>
	                  <th width="150">Dia</th>
	                  <th>Hora Inicio</th>
	                  <th>Hora Fin</th>
	                  <th>Accion</th>
	                </tr>
	              </thead>
	              <tfoot>
	                <tr>
	                  <!-- <th>Correo</th> -->
	                  <th>Materia</th>
	                  <th>Profesor</th>
	                  <th width="150">Dia</th>
	                  <th>Hora Inicio</th>
	                  <th>Hora Fin</th>
	                  <th>Accion</th>
	                </tr>
	              </tfoot>
	              <tbody>

	              </tbody>
	            </table>
	          <!-- </div> -->
	      </div>
	    <!-- </div> -->
	</div>

  	<hr>
	
    <div class="form-group row">
	  	<div class="col-sm-6 mb-3 mb-sm-0">
	    
		    <% if @section.id %>
		      <% if can? :update, Section %>
		          <%= f.submit "Editar", class:'btn btn-primary btn-sm' %>
		      <% end %>

		      <% if can? :read, Section %>
		        <%= link_to "Ver" , admin_section_path(@section), :class => 'btn btn-sm btn-warning shadow-sm' %>
		      <% end %>
		    <% else %>
		      <% if can? :create, Section %>
		        <%= f.submit "Crear", class:'btn btn-primary btn-sm shadow-sm' %>
		      <% end %>
		    <% end %>
		    <% if can? :read, Section %>
		        <%= link_to 'Cancel', url_for(:back), :class => 'btn btn-sm btn-light shadow-sm' %>
		    <% end %>
		    
		    <br>
	  	</div>
    </div>




<% end %>

<!-- Modal-->
<div class="modal fade" id="ModalMessage" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"> </h5>
        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">
        
      </div>
      <div class="modal-footer">
        <center>
          <button class="d-none d-sm-inline-block btn btn-sm btn-light shadow-sm" type="button" data-dismiss="modal">Cancel</button>
        </center>
      </div>
    </div>
  </div>
</div>

app/views/admin/sections/index.html.erb
  <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-2 text-gray-800">Secciones</h1>
    <a href="<%= new_admin_section_path  %>" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fa fa-plus fa-sm text-white-50"></i> Crear Seccion</a>
    <!-- <a href="<%= new_admin_news_path  %>"><button class="btn btn-primary btn-sm"><i class="fa fa-plus fa-sm text-white-50"></i> Crear Anuncio</button></a> -->
  </div>

  <%= render 'admin/home/messages' if !flash.empty? %>

 

  
  <!-- DataTales Example -->
  <div class="col-lg-12 col-md-12 col-xs-12">
    <!-- <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">DataTables Example</h6>
    </div> -->
    <!-- <div class="card-body"> -->
        <table class="table table-striped table-responsive-md btn-table table-bordered" id="dataTable" width="100%" cellspacing="0">
          <thead>
            <tr>
              <th><center>Nombre</center></th>
              <th class="d-none d-sm-table-cell"><center>Estudiantes</center></th>
              <th width="225"><center>Acciones</center></th>
            </tr>
          </thead>
          <tfoot>
            <tr>
              <th><center>Nombre</center></th>
              <th class="d-none d-sm-table-cell"><center>Estudiantes</center></th>
              <th width="225"><center>Acciones</center></th>
            </tr>
          </tfoot>
          <tbody>
            <% @sections.each do |section| %>
              <tr>
                <td><center><%= section.description %></center></td>
                <td class="d-none d-sm-table-cell">
                  <center>
                    <select class="browser-default custom-select"> 
                      <option selected="selected">Estudiantes de <%= section.description %></option>
                      <% @users_section.each do |us| %>
                        <% @users.each do |user| %>
                          <% if (user.id == us.user_id) and (us.section_id == section.id) %>
                            <option><%= user.name %> <%= user.lastname %></option>
                          <% end %> 
                        <% end %>
                      <% end %>
                    </select> 
                  </center>
                </td>
                <td>
                  <center>
                    <% if can? :read, Section %>
                      <a href="<%= admin_section_path(section)%>"><button class="btn-floating btn-sm btn-outline-info shadow-sm" data-placement="botton" title="Detalle <%= section.description %>"><i class="fas fa-fw fa-eye"></i></button></a>
                    <% end %>
                    <% if can? :update, Section %>
                      <a href="<%=edit_admin_section_path(section)%>"><button class="btn-floating btn-sm btn-outline-primary shadow-sm" data-placement="botton" title="Editar <%= section.description %>"><i class="fas fa-fw fa-edit"></i></button></a>
                    <% end %>
                    <% if can? :destroy, Section %>
                    <button class="btn-floating btn-sm btn-outline-danger shadow-sm" href="#"  data-placement="botton" title="Eliminar <%= section.description %>" data-datac="<%= admin_section_path(section) %>,<%= section.description %>" ><i class="fas fa-fw fa-trash"></i></button>
                    <% end %>
                  </center>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
    <!-- </div> -->
  </div>


  <!-- Logout Modal-->
  <div class="modal fade" id="DeleteSection" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Eliminar Seccion?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">
          

          </div>
        <div class="modal-footer" id="myModalFooter">
          <button class="d-none d-sm-inline-block btn btn-sm btn-light shadow-sm" type="button" data-dismiss="modal">Cancel</button>
          <!-- <a class="btn btn-primary" href="login.html">Logout</a> -->
          <!-- <a class="d-none d-sm-inline-block btn btn-sm btn-danger shadow-sm" rel="nofollow" data-method="delete" href="/admin/sections/26">Eliminar</a> -->

          </div>
      </div>
    </div>
  </div>




<script type="text/javascript">
  
  $(document).ready(function () {
    $('#dataTable').DataTable();
    $('.dataTables_length').addClass('bs-select');
  });

  $('.btn-floating.btn-sm.btn-outline-danger.shadow-sm').click(function() {
    var d = $(this).data('datac');      
    //alert(d); 
    button = '<a class="d-none d-sm-inline-block btn btn-sm btn-danger shadow-sm" rel="nofollow" data-method="delete" href="'+d.split(",")[0]+'">Eliminar</a>';
    msg = 'Esta seguro de Eliminar la Seccion '+d.split(",")[1];
    $modal = $('#DeleteSection');
    $modal.find('.modal-title').text('' + 'Eliminar seccion?');
    $modal.find('.modal-body').text(''+ msg);

    $(".d-none.d-sm-inline-block.btn.btn-sm.btn-danger.shadow-sm").remove(); //Con esta linea elimino en el modal un button parecido al que realizara la accion de eliminar.
    
    $( "#myModalFooter" ).append(button);
    $modal.modal('show');
  });
  
</script>

app/views/admin/sections/show.html.erb
	
	<div class="d-sm-flex align-items-center justify-content-between mb-4">
		<h1 class="h3 mb-0 text-gray-800">Seccion: <%= @section.description %></h1>
	</div>

	<div class="row">
		<div class="col-lg-12 col-md-12 col-xs-12">

			<!-- Collapsable Card Example -->
			<!-- <div class="card shadow mb-4"> -->
			<!-- Card Header - Accordion -->
				<a href="#collapseCardExample1" class="d-block card-header py-3" data-toggle="collapse" role="button" aria-expanded="true" aria-controls="collapseCardExample1">
					<h6 class="m-0 font-weight-bold text-dark">Estudiantes</h6>
				</a>
				<!-- Card Content - Collapse -->
				<div class="collapse show" id="collapseCardExample1">
					<!-- <div class="card-body"> -->
					<strong>
						<!-- <div class="card-body"> -->
				            <table class="table table-striped table-bordered" id="dataTable" width="100%" cellspacing="0">
				              <thead>
				                <tr>
				                  <th><center>Correo</center></th>
				                  <th><center>Nombre</center></th>
				                  <th><center>ID</center></th>
				                </tr>
				              </thead>
				              <tfoot>
				                <tr>
				                  <th><center>Correo</center></th>
				                  <th><center>Nombre</center></th>
				                  <th><center>ID</center></th>
				                </tr>
				              </tfoot>
				              <tbody>
				              	<% @users_section.each do |us| %>
					              	<tr>
					              		<td><center><%= us.email %></center></td>
					              		<td><center><%= us.name %> <%= us.lastname %></center></td>
					              		<td><center><%= us.dni %></center></td>
					              	</tr>
				              	<% end %>
				              </tbody>
				            </table>
				        <!-- </div> -->
					</strong>
					<!-- </div> -->
				</div>
			<!-- </div> -->
		</div>

		<div class="col-lg-12 col-md-12 col-xs-12">

			<!-- Collapsable Card Example -->
			<!-- <div class="card shadow mb-4"> -->
			<!-- Card Header - Accordion -->
				<a href="#collapseCardExample2" class="d-block card-header py-3" data-toggle="collapse" role="button" aria-expanded="true" aria-controls="collapseCardExample2">
					<h6 class="m-0 font-weight-bold text-dark">Profesores y Materias</h6>
				</a>
				<!-- Card Content - Collapse -->
				<div class="collapse show" id="collapseCardExample2">
					<!-- <div class="card-body"> -->
					<strong>
						<!-- <div class="card-body"> -->
				            <table class="table table-striped table-bordered" id="dataTable2" width="100%" cellspacing="0">
				              <thead>
				                <tr>
				                  <!-- <th>Correo</th> -->
				                  <th><center>Materia</center></th>
				                  <th><center>Dia</center></th>
				                  <th><center>Profesor</center></th>
				                  <th><center>Hora de Inicio</center></th>
				                  <th><center>Hora de Fin</center></th>
				                </tr>
				              </thead>
				              <tfoot>
				                <tr>
				                  <!-- <th>Correo</th> -->
				                  <th><center>Materia</center></th>
				                  <th><center>Dia</center></th>
				                  <th><center>Profesor</center></th>
				                  <th>Hora de Inicio</th></th>
				                  <th><center>Hora de Fin</center></th>
				                </tr>
				              </tfoot>
				              <tbody>
				              	<% @sps.each do |sps| %>
									<tr>
										<td><center><%= sps.sbname %></center></td>
										<td><center><%= sps.day %></center></td>
										<td><center><%= sps.name %> <%= sps.lastname %></center></td>
										<td><center><%= sps.time_init == 6.0 ? '6am' : sps.time_init == 7.0 ? '7am' : sps.time_init == 8.0 ? '8am' : sps.time_init == 9.0 ? '9am' : sps.time_init == 10.0 ? '10am' : sps.time_init == 11.0 ? '11am' : sps.time_init == 12.0 ? '12m' : sps.time_init == 13.0 ? '1pm' : sps.time_init == 14.0 ? '2pm' : sps.time_init == 15.0 ? '3pm' : sps.time_init == 16.0 ? '4pm' : sps.time_init == 17.0 ? '5pm' : sps.time_init == 18.0 ? '6pm' : 'Indefinido'%></center></td>
										<td><center><%= sps.time_end == 6.0 ? '6am' : sps.time_end == 7.0 ? '7am' : sps.time_end == 8.0 ? '8am' : sps.time_end == 9.0 ? '9am' : sps.time_end == 10.0 ? '10am' : sps.time_end == 11.0 ? '11am' : sps.time_end == 12.0 ? '12m' : sps.time_end == 13.0 ? '1pm' : sps.time_end == 14.0 ? '2pm' : sps.time_end == 15.0 ? '3pm' : sps.time_end == 16.0 ? '4pm' : sps.time_end == 17.0 ? '5pm' : sps.time_end == 18.0 ? '6pm' : 'Indefinido'%></center></td>
									</tr>
				              	<% end %>
				              </tbody>
				            </table>
				        <!-- </div> -->
					</strong>
					<!-- </div> -->
				</div>
			<!-- </div> -->
		</div>
	</div>

	<div class="form-group">
		<hr>
	    <div class="col-lg-12 col-md-12 col-xs-12">
			<%= link_to 'Cancelar', url_for(:back), :class => 'btn btn-sm btn-light shadow-sm' %>
			<%= link_to 'Editar', edit_admin_section_path(@section), :class => 'btn btn-sm btn-primary shadow-sm' %>
		</div>
	</div>



<script type="text/javascript">
  $(document).ready(function () {

    $('#dataTable').DataTable();
    $('#dataTable2').DataTable();

    $('.dataTables_length').addClass('bs-select');
  

  });
</script>