config/routes.rb
Rails.application.routes.draw do

  # Root page
  root 'home#index'

  # Foros y comentarios
  # resources :sections do
  #   resources :forums do
  #     resources :coments
  #   end
  # end

  # Foros 
  resources :forums do
    resources :comments
  end

  # Ads (anuncios)
  resources :ads

  # Archivos y calificaciones
  resources :archives

  resources :alumnos
  resources :personals
   
  get '/return_tought' => 'home#return_tought', :as => :return_tought

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions:      'users/sessions'
  }

  devise_scope :user do
    get 'access',        to: 'users/registrations#access'
    put 'access_update', to: 'users/registrations#access_update'
  end

  namespace :admin do
    resources :news, only:[:index, :new, :create, :edit, :update, :destroy]
    resources :subjects
    resources :users, only:[:index, :new, :create, :edit, :update, :destroy]
    resources :sections
    resources :thoughts, only:[:index, :new, :create, :edit, :update, :destroy]
    resources :emails, only:[:index, :destroy]
    get "students_users_with_not_section" => "sections#students_users_with_not_section", :as => :students_users_with_not_section
    get "professors_with_subjects" => "sections#professors_with_subjects", :as => :professors_with_subjects
    get "section_professor_consult/:id" => "sections#section_professor_consult", :as => :section_professor_consult
    patch  "reset_password/:id" => "users#reset_password", :as => :reset_password
    get "send_email_representing" => "users#send_email_representing", :as => :send_email_representing
    get "send_mm_email" => "users#send_mm_email", :as => :send_mm_email
    get "send_ms_email" => "users#send_ms_email", :as => :send_ms_email
    get "check_mode" => "admin#check_mode", :as => :check_mode
    get "update_mode" => "admin#update_mode", :as => :update_mode
  end

  
  # devise_for :users
  # get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  match '*path' => 'application#error_redirect', via: :all
end

app/controllers/home_controller.rb
class HomeController < PublicController
  
  @id_tought = 0

  def index
  	#@news = New.pluck(:id, :name, :date_init, :date_end, :created_at, :updated_at)
  	@news =	New.select("id as id, name as title, description as description, date_init as start, date_end + 1  as end")

  	@users = User.where(id: UserRole.where(role_id: Role.where(name: ['Administrativo', 'Profesor', 'Superadmin']).pluck(:id)).pluck(:user_id))
  	@user_roles = UserRole.where(role_id: Role.where(name: ['Administrativo', 'Profesor', 'Superadmin']))
  	@roles = Role.where(name: ['Administrativo', 'Profesor', 'Superadmin'])

  	#Recordar despues colocar Status Activo
  	count = Thought.count
  	random_offset = rand(count)
  	@thought = Thought.offset(random_offset).first
    @id_thought = @thought.id
  end


  def return_tought
    @thought = Thought.limit(1).order("RANDOM()")
    while @thought.ids == @id_thought do
      @thought = Thought.limit(1).order("RANDOM()")
    end
    @id_thought = @thought.ids
    render :json => (@thought)
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_about.html.erb
<section id="about">
  <div class="container">
    <div class="row about-container">

      <div class="col-lg-6 content order-lg-1 order-2">
        <h2 class="title">Acerca de Nosotros</h2>
        <p>
              Hace mucho tiempo, llego a esta ciudad una dama trujillana, docente de gran calidad humana y amante de los niños, que quiso continuar en esta capital la labor de educadora que ya ejercía en su tierra natal. Para el año de 1961, abre sus puertas a un preescolar que identificó,  como: “Caperucita” en la Urbanización El Marqués, calle Guaicaipuro, Qta. “La Aguadita”.

              En el recorrer de los años voces infantiles llenaron sus aulas y poco a poco el Kinder Caperucita fue creciendo y en el mes de Octubre de 1.971, bajo el N° 15 fue inscrito en el Ministerio de Educación con el nombre de “Colegio Cruz Carrillo”, en honor al <a href="https://es.wikipedia.org/wiki/Jos%C3%A9_de_la_Cruz_Carrillo" target="blank">prócer Trujillano</a>. Para la presente fecha, funciona en la Calle Naiguatá, Quinta “La Negra”, Urb. El Marqués y cuenta con el nivel de Educación Básica I-II-III Etapa, también cuenta con el  nivel de Educación Media Diversificada (Ciencias).

              Por sus aulas han pasado millares de jóvenes, hoy profesionales que en los distintos campos del saber humano, contribuyen con el desarrollo económico,  político y social del país. De igual forma,  el plantel ha contado con grandes profesionales de la docencia y iempre  estuvo bajo la tutela de su fundadora la Señorita Ana Julia Pimentel, quien aunque físicamente no nos acompaña, espiritualmente fortalece día a día la obra fundadora de juventudes que en el colegio se lleva a cabo.
        </p>

        <div class="icon-box wow fadeInUp">
          <div class="icon"><i class="fa fa-tasks"></i></div>
          <h4 class="title"><a href="">Misión</a></h4>
          <p class="description">Formar ciudadanos integrales y responsables con valores de tolerancia, respeto y aceptación a las diferencias, para que sean útiles a la sociedad, como base fundamental en la formación de las familias con conociminetos sólidos.</p>
        </div>

        <div class="icon-box wow fadeInUp" data-wow-delay="0.2s">
          <div class="icon"><i class="fa fa-heart"></i></div>
          <h4 class="title"><a href="">Valores</a></h4>
          <p class="description">Nos centramos principalmente en la educación de los estudiantes, estos son: Honestidad, Gratitud, Solidaridad, Dencencia, Prudencia, Puntualidad, Servicio, Sacrifio, Superación, 
          Comprensión y sobre todo el Amor de aceptar, servir y cuidar a sus valiosos estudiantes.</p>
        </div>

        <div class="icon-box wow fadeInUp" data-wow-delay="0.4s">
          <div class="icon"><i class="fa fa-binoculars"></i></div>
          <h4 class="title"><a href="">Visión</a></h4>
          <p class="description">Ser una Institución Educativa que favorezca el desarrollo humano en la formación integral, ética y moral, a partir de la sensibilidad, diversidad y pluralidad, para que el conocimiento contribuya al éxito en la vida.</p>
        </div>

      </div>

      <div class="col-lg-6 background order-lg-2 order-1 wow fadeInRight"></div>
    </div>

  </div>
</section>

app/views/home/_call-to-action.html.erb
<link href="https://fonts.googleapis.com/css?family=Lobster|Dancing+Script|Pacifico|Satisfy|Courgette|Caveat|Great+Vibes|Gloria+Hallelujah|Cookie|Butterfly+Kids|Tangerine|Sacramento|Monoton|Handlee|Marck+Script|analei|Parisienne&display=swap" rel="stylesheet">



<section id="call-to-action">
  <div class="container wow fadeIn">
    <div class="row" id="divThought">
      <div class="col-lg-9 text-center text-lg-left">
        <h3 class="cta-title" id="ThoughtH3">"<% if @thought %>
          <%= @thought.thought %>" <% else %> Pensamiento <% end %></h3>
        <p class="cta-text" id="authorPensamiento">
          <% if @thought %>
            <%= @thought.author %>
          <% else %> 
            Author 
          <% end %>
        </p>
      </div> 
      <div class="col-lg-3 cta-btn-container text-center">
        <a class="cta-btn align-middle" id="RefreshPensamiento"><i class="fa fa-circle-o-notch"></i></a>
        <!-- <a><button class="cta-btn align-middle" href="#" id="RefreshPensamiento" style="background-color: #2dc997; border: 0.5px;"><i class="fas fa-sync-alt"></i> </button></a> -->
      </div>
    </div>

  </div>
  
</section>

<script type="text/javascript">
  
  $("#RefreshPensamiento").click(function(){
    var author = null;
    var thought = null;

    //$('#ThoughtH3').text(thought).delay( 800 ).fadeOut();
    //$('p#authorPensamiento').text(author).delay( 800 ).fadeOut();

    //alert('Entre');
    $.ajax({
      type: "GET",
      dataType: "json",
      url: "<%= return_tought_path %>",
      success: function (data) {
        $.each(data, function(index, element) {
            author = element.author;
            thought = '"'+element.thought+''+'"';
        });
        var font = return_font();
        //$("#divThought").fadeIn( 8000, function() {
          $('#ThoughtH3').css('font-style', 'italic');
          $('#ThoughtH3').css('color', 'white');
          $('#ThoughtH3').css('font-family', font);
          $('#ThoughtH3').css('font-size', '50px');
          $('#ThoughtH3').text(thought);
          $('p#authorPensamiento').css('color', 'white');
          $('p#authorPensamiento').css('font-family', font);
          $('#ThoughtH3').css('font-size', '40px');
          //console.log("Author: "+author+" Pensamiento: "+thought);
          $('p#authorPensamiento').text(author);
        //});
        
      },
      error: function (data) {
          console.log("Ha ocurrido un error: "+data);
      }
    });
  });

  function return_font(){
    var Dancing_Script = 'Dancing Script, cursive';
    var Lobster = 'Lobster, cursive';
    var Pacifico = 'Pacifico, cursive';
    var Satisfy = 'Satisfy, cursive';
    var Courgette = 'Courgette, cursive';
    var Caveat = 'Caveat, cursive';
    var Great_Vibes = 'Great Vibes, cursive';
    var Gloria_Hallelujah = 'Gloria Hallelujah, cursive';
    var Cookie = 'Cookie, cursive';
    var Butterfly_Kids = 'Butterfly Kids, cursive';
    var Tangerine = 'Tangerine, cursive';
    var Sacramento = 'Sacramento, cursive';
    var Monoton = 'Monoton, cursive';
    var Handlee = 'Handlee, cursive';
    var Marck_Script = 'Marck Script, cursive';
    var Hanalei = 'Hanalei, cursive';
    var Parisienne = 'Parisienne, cursive';

    var fonts = [Dancing_Script,Lobster,Pacifico,Satisfy,Courgette,Caveat,Great_Vibes,Gloria_Hallelujah,Cookie,Butterfly_Kids,Tangerine,Sacramento,Monoton,Handlee,Marck_Script,Hanalei,Parisienne];

    var font = fonts[Math.floor(Math.random()*fonts.length)];
    
    //console.log(font);
    return font;
  }

</script>

<!--script>

  // var btn = $("#RefreshPensamiento");
  // //console.log(btn);
  // setInterval(function(){
  //   btn.click();
  // },10000);
</script-->

app/views/home/_contact.html.erb
<section id="contact">
  <div class="container wow fadeInUp">
    <div class="section-header">
      <h3 class="section-title text-white">Contacto</h3>
      <p class="section-description text-white">Comuniquese con nosotros a través de nuestros correos o llamenos, siempre estaremos prestos a atenderles.</p>
    </div>
  </div>

  <!-- Uncomment below if you wan to use dynamic maps -->
  <iframe src="https://www.google.com/maps/embed/v1/place?q=Colegio+Cruz+Carrillo&key=AIzaSyBFw0Qbyq9zTFTd-tUY6dZWTgaQzuU17R8" width="100%" height="380" frameborder="0" style="border:0" allowfullscreen></iframe>

  <div class="container wow fadeInUp mt-5">
    <div class="row justify-content-center">

      <div class="col-lg-3 col-md-4">

        <div class="info">
          <center>
            <div>
              <i class="fa fa-map-marker"></i>
              <p class="text-white">Calle Naiguatá - Miranda<br>Caracas, Ccs 1071</p>
            </div>

            <div>
            
                <i class="fa fa-envelope text-white"></i>
                <p class="text-white">acccrucarrillo@gmail.com</p> 

                <i class="fa fa-envelope-o"></i>
                <p class="text-white">colegiocruzcarrilloweb@gmail.com</p>
       
            </div>

            <div>
              <i class="fa fa-phone text-white"></i>
              <p class="text-white">+58 212 234 2191</p>
            </div>
          </center>
        </div>

        <!--div class="social-links">
          <center>
            <a href="#" class="twitter" target="_blank"><i class="fa fa-twitter"></i></a>
            <a href="#" class="facebook" target="_blank"><i class="fa fa-facebook"></i></a>
            <a href="#" class="instagram" target="_blank"><i class="fa fa-instagram"></i></a>
            <a href="#" class="google-plus" target="_blank"><i class="fa fa-google-plus"></i></a>
          </center>
        </div-->

        <!--div class="social-links">
          <center>
            <a href="#" class="pinterest" target="_blank"><i class="fa fa-pinterest-square"></i></a>
            <a href="http://www.colegiocruzcarrillo.com.ve/" class="google-plus" target="_blank" data-placement="botton" title="EduRest"><i class="fa fa-graduation-cap"></i></a>
            <a href="https://www.mozilla.org/es-ES/firefox/new/" class="google-plus" data-placement="botton" title="Le recomendamos usar el Navegador Firefox" target="_blank"><i class="fa fa-firefox"></i></a>
          </center-->
        </div>

      </div>
    </div>

  </div>
</section><!-- #contact -->

app/views/home/_facts.html.erb
<section id="facts">
  <div class="container wow fadeIn">
    <div class="section-header">
      <h3 class="section-title">Facts</h3>
      <p class="section-description">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque</p>
    </div>
    <div class="row counters">

			<div class="col-lg-3 col-6 text-center">
        <span data-toggle="counter-up">232</span>
        <p>Clients</p>
			</div>

      <div class="col-lg-3 col-6 text-center">
        <span data-toggle="counter-up">521</span>
        <p>Projects</p>
			</div>

      <div class="col-lg-3 col-6 text-center">
        <span data-toggle="counter-up">1,463</span>
        <p>Hours Of Support</p>
			</div>

      <div class="col-lg-3 col-6 text-center">
        <span data-toggle="counter-up">15</span>
        <p>Hard Workers</p>
			</div>

		</div>

  </div>
</section>

app/views/home/_footer.html.erb
<footer id="footer">
  <div class="footer-top">
    <div class="container">

    </div>
  </div>

  <div class="container">
    <div class="copyright">
      &copy; Copyright <strong><a href="https://mdbootstrap.com/education/bootstrap/"> Cruz Carrillo</a></strong>. All Rights Reserved
    </div>
    <div class="credits">
      <!--
        All the links in the footer should remain intact.
        You can delete the links only if you purchased the pro version.
        Licensing information: https://bootstrapmade.com/license/
        Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=Regna
      -->
      <!-- Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a> -->
    </div>
  </div>
</footer>

app/views/home/_header.html.erb
<header id="header">
    <div class="container">

      <div id="logo" class="pull-left">
        <a id="logoimg" class="navbar-brand2" href="#hero">Colegio Cruz Carrillo
        	<!-- <img src="/images/LogoMakr_2iVaMJ.png" alt="" title="" /></img> -->
        </a>
        <!-- Uncomment below if you prefer to use a text logo -->
        <!--<h1><a href="#hero">Regna</a></h1>-->
      </div>

      <nav id="nav-menu-container">
        <ul class="nav-menu">
          <li class="menu-active"><a href="#hero">Home</a></li>
          <li><a href="#about">Acerca de Nosotros</a></li>
          <li><a href="#services">Calendario</a></li>
          <li><a href="#portfolio">Nuestro Personal</a></li>
          <!-- <li><a href="#team">Team</a></li> -->
          <% if user_signed_in? %>
            <li class="menu-has-children"><a href=""><%= current_user.email %></a>
              <ul>
                <!-- <li><a href="<%= new_user_session_path %>">Ingresar al Sistema</a></li> -->
                <!-- <li class="menu-has-children"><a href="#">Drop Down 2</a>
                  <ul>
                    <li><a href="#">Deep Drop Down 1</a></li>
                    <li><a href="#">Deep Drop Down 2</a></li>
                    <li><a href="#">Deep Drop Down 3</a></li>
                    <li><a href="#">Deep Drop Down 4</a></li>
                    <li><a href="#">Deep Drop Down 5</a></li>
                  </ul>
                </li>

                <li><a href="#">Drop Down 3</a></li>
                 -->
                  <!--li><a href="#"><%#= current_user.is_admin? %></a></li>
                  <li><a href="#"><%#= current_user.is_administrativo? %></a></li>
                  <li><a href="#"><%#= current_user.is_profesor? %></a></li>
                  <li><a href="#"><%#= current_user.is_student? %></a></li>
                  <li><a href="#"><%#= current_user.is_representing? %></a></li-->
                  
                  <% if current_user.is_admin? %>
                    <li>
                      <a href="<%= admin_emails_path if current_user.is_admin? %>" class="waves-effect">Correos</a>
                    </li>
                    <li>
                      <a href="<%= admin_users_path if current_user.is_admin? %>" class="waves-effect">Usuarios</a>
                    </li>
                    <li>
                      <a href="<%= admin_sections_path %>" class="waves-effect">Secciones</a>
                    </li>
                    <li>
                      <a href="<%= admin_news_index_path(:status => nil) %>" class="waves-effect">Anuncios Actuales</a>
                    </li>
                    <li>
                      <a href="<%= admin_news_index_path(:status => true) %>" class="waves-effect">Anuncios Vencidos</a>
                    </li>
                    <li>
                      <a href="<%= admin_subjects_path %>" class="waves-effect">Materias</a>
                    </li>
                    <li>
                      <a href="<%= admin_thoughts_path %>" class="waves-effect">Pensamientos</a>
                    </li>

                    <li>
                      <a href="<%= forums_path %>" class="waves-effect">Foros Profesores</a>
                    </li>
                    <li>
                      <a href="<%= ads_path %>" class="waves-effect">Anuncios Profesores</a>
                    </li>
                    <li>
                      <a href="<%= archives_path %>" class="waves-effect">Archivos Profesores</a>
                    </li>
                    <!-- <li><a href="#">Drop Down 3 SuperAdmin</a></li> -->
                  <% elsif current_user.is_administrativo? %>
                    <!-- <li><a href="#">Drop Down 3 Administrativo</a></li> -->
                    <li>
                      <a href="<%= admin_emails_path %>" class="waves-effect">Correos</a>
                    </li>
                    <li>
                      <a href="<%= admin_users_path %>" class="waves-effect">Usuarios</a>
                    </li>
                    <li>
                      <a href="<%= admin_sections_path %>" class="waves-effect">Secciones</a>
                    </li>
                    <li>
                      <a href="<%= admin_news_index_path(:status => nil) %>" class="waves-effect">Anuncios Actuales</a>
                    </li>
                    <li>
                      <a href="<%= admin_news_index_path(:status => true) %>" class="waves-effect">Anuncios Vencidos</a>
                    </li>
                    <li>
                      <a href="<%= admin_subjects_path %>" class="waves-effect">Materias</a>
                    </li>
                    <li>
                      <a href="<%= admin_thoughts_path %>" class="waves-effect">Pensamientos</a>
                    </li>
                  <% elsif current_user.is_profesor? %>
                    
                    <li>
                      <a href="<%= forums_path %>" class="waves-effect">Foros</a>
                    </li>
                    <li>
                      <a href="<%= ads_path %>" class="waves-effect">Anuncios</a>
                    </li>
                    <li>
                      <a href="<%= archives_path %>" class="waves-effect">Archivos y/o calificaciones</a>
                    </li>


                    <!--li class="nav-item dropright notifications-nav">
                      <a class="nav-link dropdown-toggle waves-effect" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span class="text-dark">Área de profesores</span>
                      </a>

                      <div class="dropdown-menu dropdown-primary" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="<%= forums_path %>">
                          <i class="fas fa-chalkboard-teacher mr-2" aria-hidden="true"></i>
                          <span>Foros</span>
                        </a>

                        <a class="dropdown-item" href="<%= ads_path %>">
                          <i class="fas fa-sms mr-2" aria-hidden="true"></i>
                          <span>Anuncios</span>
                        </a>

                        <a class="dropdown-item" href="<%= archives_path %>">
                          <i class="fas fa-award mr-2" aria-hidden="true"></i>
                          <span>Archivos y/o calificaciones</span>
                        </a>
                      </div>
                    </li-->

                  <% elsif current_user.is_student? %>
                    <li>
                      <a href="<%= forums_path %>" class="waves-effect">Foros</a>
                    </li>
                    <li>
                      <a href="<%= ads_path %>" class="waves-effect">Anuncios</a>
                    </li>
                    <li>
                      <a href="<%= archives_path %>" class="waves-effect">Archivos y/o calificaciones</a>
                    </li>


                    <!--li class="nav-item dropright dropdown-item">
                      <a class="nav-link dropdown-toggle waves-effect" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Área de estudiantes
                      </a>

                      <div class="dropdown-menu dropdown-primary" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="<%= forums_path %>">
                          <i class="fas fa-chalkboard-teacher mr-2" aria-hidden="true"></i>
                          <span>Foros</span>
                        </a>

                        <a class="dropdown-item" href="<%= ads_path %>">
                          <i class="fas fa-sms mr-2" aria-hidden="true"></i>
                          <span>Anuncios</span>
                        </a>

                        <a class="dropdown-item" href="<%= archives_path %>">
                          <i class="fas fa-award mr-2" aria-hidden="true"></i>
                          <span>Archivos y/o calificaciones</span>
                        </a>
                      </div>
                    </li-->
                  <% elsif current_user.is_representing? %>
                    <li><a href="#">AREA DE REPRESENTANTES, PRONTO OPERATIVA</a></li>
                  <% end %>

                  <li>
                    <%= link_to 'Cerrar Session', destroy_user_session_path, method: :delete, class:'dropdown-item' %>
                  </li>
                <!-- <li><a href="#">Drop Down 5</a></li> -->
              </ul>
            </li>
          <% else %>
            <li class="menu-has-children"><a href="">Ingreso</a>
              <ul>
                <li><a href="<%= new_user_session_path %>">Ingresar al Sistema</a></li>
                <!-- <li class="menu-has-children"><a href="#">Drop Down 2</a>
                  <ul>
                    <li><a href="#">Deep Drop Down 1</a></li>
                    <li><a href="#">Deep Drop Down 2</a></li>
                    <li><a href="#">Deep Drop Down 3</a></li>
                    <li><a href="#">Deep Drop Down 4</a></li>
                    <li><a href="#">Deep Drop Down 5</a></li>
                  </ul>
                </li>
                <li><a href="#">Drop Down 3</a></li>
                 --><li><a href="<%= new_user_password_path %>">Olvidó su Constraseña</a></li>
                <!-- <li><a href="#">Drop Down 5</a></li> -->
              </ul>
            </li>
          <% end %>
          
          <li><a href="#contact">Contacto</a></li>
        </ul>
      </nav><!-- #nav-menu-container -->
    </div>
  </header><!-- #header -->

app/views/home/_hero.html.erb
<section id="hero">
	<div class="hero-container">
	  <h1>Bienvenidos al Colegio Cruz Carrillo</h1>
	  <h2>Somos una Institución Educativa</h2>
	  <a href="#about" class="btn-get-started">Comenzar</a>
	</div>
</section>

app/views/home/_portfolio.html.erb
<section id="portfolio">
  <div class="container wow fadeInUp">
    <div class="section-header">
      <h3 class="section-title">Nuestro Personal</h3>
      <!-- <p class="section-description">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque</p> -->
    </div>
    <div class="row">

      <div class="col-lg-12">
        <ul id="portfolio-flters">
          <li data-filter=".filter-app, .filter-card, .filter-logo, .filter-web" class="filter-active">All</li>
          <li data-filter=".filter-app">Administrativo</li>
          <li data-filter=".filter-card">Profesor</li>
          <!-- <li data-filter=".filter-logo">Adminstrador de la Pagina</li> -->
          <li data-filter=".filter-web">Adminstrador de la Pagina</li>
        </ul>
      </div>
    </div>

    <div class="row" id="portfolio-wrapper">
      
      <% @users.each do |user| %>
        
            
            <% if user.roles.first.name == "Profesor" or user.is_profesor?%>
              <div class="col-lg-3 col-md-6 portfolio-item filter-card">
                  <%if user.message != nil %> <a onclick="displayMsg('<%= user.name %> <%= user.lastname %>','<%= user.message%>');" title="<%= user.name %> <%= user.lastname %>: <%= user.message%>"> <% else %> <a> <%end%>
                    <img src="/images/img/portfolio/educador.jpg" alt="">
            <% elsif user.roles.first.name == "Administrativo" %>
              <div class="col-lg-3 col-md-6 portfolio-item filter-app">
                <%if user.message != nil %> <a onclick="displayMsg('<%= user.name %> <%= user.lastname %>','<%= user.message%>');" title="<%= user.name %> <%= user.lastname %>: <%= user.message%>"> <% else %> <a> <%end%> 
                  <img src="/images/img/portfolio/administrativo.jpeg" alt="">
            <% elsif user.roles.first.name == "Superadmin" %>
              <div class="col-lg-3 col-md-6 portfolio-item filter-web">
                <%if user.message != nil %> <a onclick="displayMsg('<%= user.name %> <%= user.lastname %>','<%= user.message%>');" title="<%= user.name %> <%= user.lastname %>: <%= user.message%>"> <% else %> <a> <%end%>  
                  <img src="/images/img/portfolio/superadmin.jpeg" alt="">
            <% end %>
            
            <div class="details">
              <h4><%= user.roles.first.name %></h4>

                <span><%= user.name %> <%= user.lastname %></span>
                            
            </div>
          </a>
        </div>
      <% end %>
    </div>
  </div>
</section>
  
<div id="ModalProfMsg" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">

                <h4 id="modalTitleModalProfMsg" class="modal-title"></h4>

                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true" class="black-text">&times;</span>
            </button>
            </div>

            <div id="modalBodyModalProfMsg" class="modal-body"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-sm btn-outline-primary" data-dismiss="modal">Aceptar</button>
                <!-- <button class="btn btn-primary"><a id="eventUrl" target="_blank">Event Page</a></button> -->
            </div>
        </div>
    </div>
</div>


<script>
    
    function displayMsg(title, msg){
      console.log('tile: '+title+'msg: '+msg);
      $('#modalTitleModalProfMsg').html(title);
      $('#modalBodyModalProfMsg').html(msg);
      $('#ModalProfMsg').modal();
    }

</script>